name: Publish Next

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Which package to publish'
        required: true
        type: choice
        options:
          - api-models
          - api-core
          - api-processors
          - api-service
          - api-rest-client
          - api-server-fastify
          - api-auth-entity-storage-models
          - api-auth-entity-storage-service
          - api-auth-entity-storage-rest-client

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
       id-token: write

    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: next

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Remove Mono-Repo Node Modules
        run: |
          rm package.json
          rm package-lock.json

      - name: Check package version contains -next
        run: |
          cd packages/${{ github.event.inputs.package }}
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          echo Package Version $PACKAGE_VERSION
          if [[ $PACKAGE_VERSION != *"-next"* ]]; then
            echo "Error: package version does not contain -next"
            exit 1
          fi

      - name: Run Dist
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm install
          npm run dist

      - name: Cleanup package properties
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm pkg delete scripts
          npm pkg delete devDependencies

      - name: Publish
        run: |
          cd packages/${{ github.event.inputs.package }}
          npm publish --provenance --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
